### ISSUE TITLE
Your Past

### ISSUE THREAD

**Issue by mxstbr** [jkup/ama#1]
How did you become a developer? What was your path, what's your raw story?

**Comment by jkup** [comment]
I started about 7 years ago.

My very first time touching code was setting up a [phpBB](https://www.phpbb.com/) forum for a [toy company](http://www.gundamstoreandmore.com/) I worked for. I was an administrative assistant. I mostly filed papers and well, no, I exclusively filed papers.

One day we got to talking and they told me they had always wanted a forum but never quite figured out how to do it. They had some "premium" Yahoo! web hosting plan and said if I wanted to take a crack at it they had 24/7 support.

After I got the forum up and running I started looking for more coding work. I ended up finding a Craigslist ad for a web design internship at a [company in my home town](https://3.7designs.co/). I applied and they accepted (even though I had basically 0 experience). I worked there super part-time for a few months and after it was over the owner of the agency would refer clients to me from time to time.

It was awesome. I survived for over a year just off those referrals and word of mouth. I did another short internship at [a different agency](http://wojodesign.com/) but went back to freelancing.

After freelancing on and off for about two years I took my first full-time job for a [small company that did healthcare education websites](http://www.medhub.com/). They were really great but it wasn't quite the tech role I wanted. So, after a while there I accepted a job at [Barracuda Networks](https://www.barracuda.com/).

I worked on their Backup product, doing firmware at first and then eventually moving to web. That job pushed me a lot. I worked with a ton of really smart people and we had hard problems to solve.

More than anything there was this guy there named Shane who was supposed to train me up on my first few days but ended up mentoring me pretty substantially for the entire year I worked there.

After about a year [my girlfriend](https://twitter.com/kng) and I **really** wanted to move to San Francisco. I applied at Twitter and somehow kept passing through their interview process.

Every step of the way felt like a fluke (still does) but they extended me an offer and I moved out to SF. Since then it's been an amazing 2 years of learning and working on three different but great projects!

As cliché as it sounds. Moving to San Francisco really changed my career. Beyond just working at an incredible company, I've been able to meet so many inspiring people. It's so easy to attend events at companies like Google and Facebook. I'm not saying it's for everyone, but I feel like it really helped catapult my career!

**Comment by mxstbr** [comment]
Awesome, thanks for the elaborate answer!
