### ISSUE TITLE
Whats your salary in USD

### ISSUE THREAD

**Issue by AchoArnold** [jkup/ama#10]
Hey

What do you make in the industry, and do you feel that your salary commensurate's with your experience?

Thanks!

**Comment by jkup** [comment]
Sorry, I've decided I'm not going to answer this one! It's mostly because I live in an area with an outrageous cost of living and that severely skews the numbers. You can get a pretty good idea of industry pay via a service like Glassdoor.

Also pay can be really tricky because you may have some form of equity in addition to an annual salary!
