### ISSUE TITLE
Your Future

### ISSUE THREAD

**Issue by mxstbr** [jkup/ama#2]
You're at Twitter right now, which is one of the life goals of many developers. Where do you plan on going from here, how will you further your career? Startup? Open source?

**Comment by jkup** [comment]
This is a great question, it took my a while to think on it because honestly I'm not too sure. I really want to do more with open source. I love community involvement and would like to end up doing even more conference speaking, event management and general developer relations work.

I'd also like to do more in the space of education. I like blogging and making educational videos a lot and hope to do a lot more of that in the near future!
